### ISSUE TITLE
hubble status reports Max Flows 0/0 and Unavailable Nodes

### ISSUE THREAD

**Issue by joebowbeerxealth** [cilium/hubble#599]
Trying to enable hubble ui in a cluster where cilium was installed with helm:

```
cilium hubble enable --ui --create-ca --relay-version v1.10.3
```

(The `--relay-version` is a workaround for https://github.com/cilium/cilium-cli/issues/456)

After port-forward, `hubble status` reports Max Flows 0/0 and all Nodes Unavailable even though running `cilium status` in each cilium pod shows Max Flows 4095/4095.

No known workaround.

Is this another case of cilium-cli being incompatible with a helm-installed Cilium? We wouldn't have to blaze that trail if cilium-cli were able to install Cilium chained to eks-vpc-cni.

**Comment by rolinh** [comment]
> Is this another case of cilium-cli being incompatible with a helm-installed Cilium?

My guess would be yes. Generally speaking, mixing and matching cilium-cli and helm is not a good idea.

> After port-forward, hubble status reports Max Flows 0/0 and all Nodes Unavailable even though running cilium status in each cilium pod shows Max Flows 4095/4095.

Hubble-Relay fails to connect to peers for some reason. What's in Hubble-Relay's log?

**Comment by joebowbeer** [comment]
Following advice, I enabled hubble via helm and then did the following, which worked.

```
cilium status --wait
cilium hubble ui
```

**Comment by jalberto** [comment]
Already did :)
apparently previous version works correctly, the troubles begin with 1.10

**Comment by Sh4d1** [comment]
@rolinh Scaleway k8s dev here, the issue with cilium cli is that hubble relay fails to connect to the hubble port on the node. Checked a bit, and looks like cilium is starting the hubble server, but only on a socket path, and not on the intended port. Is it normal?

**Comment by rolinh** [comment]
@Sh4d1 What is Cilium's configmap? Cilium logs would also be helpful.
In Cilium v1.9 and v1.10, listening on node port 4244 is enabled by default but the agent won't start listening unless a TLS certificate is provided (mTLS is required by default). So if the Hubble server does not listen on port 4244 it either means that the listen address is not configured or that Hubble is waiting for a TLS certificate (and obviously that Hubble TLS is not disabled (=default)).

**Comment by Sh4d1** [comment]
Okay got it, we're gonna use the cronjob to generate the cert and it should work flawlessly 😄 @jalberto the fix should be in production this week I guess :)

**Comment by jalberto** [comment]
Thanks! great work :)

**Comment by Sh4d1** [comment]
@rolinh I got some `2021-09-01T14:08:26.479272492Z level=warning msg="Failed to create gRPC client" address="10.71.18.95:4244" error="context deadline exceeded" hubble-tls=true next-try-in=1h30m0s peer=scw-cilium2-default-3ae3a43267a64269a6623bd133 subsys=hubble-relay` 

Though 
```
# curl 10.71.18.95:4244
curl: (52) Empty reply from server
```

Not sure what happens here 🤔 

The cert looks good:
```
# openssl s_client -host 10.71.18.95 -port 4244 | openssl x509 -text -noout
Can't use SSL_get_servername
depth=0 CN = *.cilium2.hubble-grpc.cilium.io
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN = *.cilium2.hubble-grpc.cilium.io
verify error:num=21:unable to verify the first certificate
verify return:1
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            7e:0a:ac:c7:7f:62:10:33:9b:c0:2a:cf:f9:0a:a8:e6:d5:c8:a4:c9
        Signature Algorithm: ecdsa-with-SHA256
        Issuer: CN = hubble-ca.cilium.io
        Validity
            Not Before: Sep  1 13:37:00 2021 GMT
            Not After : Aug 31 13:37:00 2024 GMT
        Subject: CN = *.cilium2.hubble-grpc.cilium.io
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (256 bit)
                pub:
                    04:27:f2:da:bf:84:15:12:ee:eb:cb:45:55:50:8b:
                    1e:93:f2:58:a5:a4:c7:22:0e:27:09:47:21:0a:35:
                    d1:93:f3:b0:dc:d3:a8:fa:48:b4:a4:8d:5b:f5:14:
                    3d:6c:da:56:d0:6b:8a:e1:fb:18:ab:4f:50:3c:db:
140556817315136:error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate:../ssl/record/rec_layer_s3.c:1543:SSL alert number 42
                    13:30:eb:47:cb
                ASN1 OID: prime256v1
                NIST CURVE: P-256
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Extended Key Usage:
                TLS Web Server Authentication
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Subject Key Identifier:
                B9:F0:9C:85:FC:8E:2B:B1:12:36:83:57:FC:3C:10:20:34:9B:66:28
            X509v3 Authority Key Identifier:
                keyid:AB:98:44:1B:03:8A:D3:D5:06:A5:66:13:B2:8A:6E:96:77:88:8E:5F

            X509v3 Subject Alternative Name:
                DNS:*.cilium2.hubble-grpc.cilium.io
    Signature Algorithm: ecdsa-with-SHA256
         30:45:02:21:00:ad:77:9b:c6:95:85:78:3e:f9:ea:44:b0:a6:
         8a:5b:8d:b9:6b:95:e9:62:c5:08:09:da:f2:3a:41:2a:d4:4a:
         83:02:20:47:4b:7a:f7:ff:59:bc:98:43:30:90:bb:78:07:c4:
         5e:cd:d6:43:b3:bf:ac:78:9b:f7:d8:67:42:32:f0:f7:54
```

**Comment by rolinh** [comment]
@Sh4d1 Connectivity issues  are unfortunately hard to debug due to a gRPC limitation (that is addressed in the upcoming version of Cilium). Could you deploy a Hubble CLI pod by running the following:
```
kubectl apply -n kube-system -f https://raw.githubusercontent.com/cilium/cilium/master/examples/hubble/hubble-cli.yaml
```

This deploys a Hubble CLI pod with the Relay mTLS certificates mounted. This means that one can connect to a Hubble server given it's IP address and ServerName:
```
kubectl exec -it -n kube-system deployment/hubble-cli -- \
    hubble observe --server tls://${IP?}:4244 \
        --tls-server-name ${SERVERNAME?} \
        --tls-ca-cert-files /var/lib/hubble-relay/tls/hubble-server-ca.crt \
        --tls-client-cert-file /var/lib/hubble-relay/tls/client.crt \
        --tls-client-key-file /var/lib/hubble-relay/tls/client.key
```

Both `${IP}` and `${SERVERNAME}` can be obtained by either looking at the Hubble Relay Pod logs. By following this approach, we should get a more descriptive error than `context deadline exceeded`.

**Comment by Sh4d1** [comment]
wow perfect thanks :D indeed:
```
failed to connect to 'tls://10.71.118.89:4244': context deadline exceeded: connection error: desc = "transport: authentication handshake failed: x509: certificate signed by unknown authority"
```

I ran `cilium hubble enable --create-ca --ui` so I guess I need to create the CA before right? 🤔

**Comment by Sh4d1** [comment]
@rolinh is it normal that the hubble job generate a CA secret named `hubble-ca-secret` and `cilium hubble enable` is lookng for a secret name `cilium-ca` ?

**Comment by kaworu** [comment]
>  is it normal that the hubble job generate a CA secret named `hubble-ca-secret` and cilium hubble enable is lookng for a secret name `cilium-ca` ?

Yes, this is expected.

The Helm method is the most flexible allowing different CA for ClusterMesh and Hubble, while the cilium-cli approach is the simplest one (using one CA for everything). Unfortunately, that makes them incompatible for now.

In your case, one possible workaround would be to override manually the `cilium-ca` Secret using the `hubble-ca-secret` keypair as they share the same layout:

```console
% kubectl delete secrets -n kube-system cilium-ca
secret "cilium-ca" deleted
% kubectl get secrets -n kube-system hubble-ca-secret -o yaml | sed -e 's/name: hubble-ca-secret/name: cilium-ca/;/\(resourceVersion\|uid\)/d' | kubectl apply -f -
secret/cilium-ca created
```

Then, disabling Hubble and re-enabling it with the CLI should work

```console
% cilium hubble disable
🔥 Deleting Hubble UI...
🔥 Deleting Relay...
🔥 Deleting Relay certificates...
✨ Patching ConfigMap cilium-config to disable Hubble...
♻️  Restarted Cilium pods
✅ Hubble was successfully disabled.
% cilium status --wait
…
% cilium hubble enable --ui --relay-version v1.10.3
🔑 Found existing CA in secret cilium-ca
✨ Patching ConfigMap cilium-config to enable Hubble...
♻️  Restarted Cilium pods
⌛ Waiting for Cilium to become ready before deploying other Hubble component(s)...
🔑 Generating certificates for Relay...
…
✨ Deploying Relay from quay.io/cilium/hubble-relay:v1.10.3...
✨ Deploying Hubble UI...
✅ Hubble was successfully enabled!
% cilium status --wait
…
```

Please note that the next time the `hubble-generate-certs` CronJob runs, it will override the TLS certificates for both Hubble and Relay signing them with `hubble-ca-secret` (i.e. not `ciliium-ca`). Relay should continue to work, but this could bring more incompatibility with the CLI (e.g. if you were to disable then re-enable Hubble again through the CLI).

**Comment by Sh4d1** [comment]
Okay makes sense then! @jalberto I'll wait for a uniformisaation between the 2 methods before pushing anything on my side, will be easier. You can use the helm method to install hubble cert + hubble realy / UI and it should work :)

**Comment by jalberto** [comment]
@Sh4d1 do you mean this? (https://docs.cilium.io/en/v1.10/gettingstarted/hubble_setup/#hubble-setup)

```
helm upgrade cilium cilium/cilium --version 1.10.4 \
   --namespace kube-system \
   --reuse-values \
   --set hubble.relay.enabled=true \
   --set hubble.ui.enabled=true
```

I do not see this working as cilium has not been installed via helm, so there is no cilium helm to upgrade

**Comment by Sh4d1** [comment]
Nope, I meant templating the files of Hubble certgen/Hubble UI/Hubble relay, and applying only them

**Comment by jalberto** [comment]
Sorry, but I don't get it, are you referring to this? https://github.com/cilium/hubble/issues/599#issuecomment-910347082

**Comment by Sh4d1** [comment]
Nope, I am referring to https://github.com/cilium/cilium/tree/master/install/kubernetes/cilium/templates where you can template the hubble* directories (and the hubble/tls-cronjob)

**Comment by jalberto** [comment]
I guess it can be a workaround, but it also seems it can break things as soon this bug get fixed or the cluster upgrades

**Comment by Sh4d1** [comment]
I'm not sure the way to move forward on our side though:
- either we deploy hubble completey (not everybody uses it)
- we only deploy cilium, with the config ready for hubble (as long as you create the CA, certs, deploy, ...)
- we deploy cilium "hubble-ready" (with the CA and cert created) -> this might break depending on how things goes forward

I'm personally leaning towards the second one

**Comment by jalberto** [comment]
What I like of option 1:
- disabling hubble is one command away
- hubble is the only way to see what is happening in that layer (so no everybody uses it until they need it)
- as hubble is in control of SCW it can be harder to break

About option 2:
- if there are clear instructions in how to do it, can be a solution
- if all those moving parts need to be created manually, it can drive the same issue as in option 3

**Comment by jalberto** [comment]
@Sh4d1 any progress on this?

**Comment by samstride** [comment]
Hi,

I have this issue too.

I use k3s `v1.22.7` on a single node and I installed cilium `v1.11.0` via the CLI.

I later upgraded to cilium `v1.11.3` using `kubectl + helm template` as described in the [docs](https://docs.cilium.io/en/stable/operations/upgrade/).

I then installed hubble as follows:

```
cilium hubble enable --ui
🔑 Found CA in secret cilium-ca
✨ Patching ConfigMap cilium-config to enable Hubble...
♻️  Restarted Cilium pods
⌛ Waiting for Cilium to become ready before deploying other Hubble component(s)...
🔑 Generating certificates for Relay...
✨ Deploying Relay from quay.io/cilium/hubble-relay:v1.11.3...
✨ Deploying Hubble UI from quay.io/cilium/hubble-ui:v0.8.5 and Hubble UI Backend from quay.io/cilium/hubble-ui-backend:v0.8.5...
⌛ Waiting for Hubble to be installed...
✅ Hubble was successfully enabled!
```

However, hubble status shows 0 connected nodes:

```
hubble status
Healthcheck (via localhost:4245): Ok
Current/Max Flows: 0/0
Flows/s: N/A
Connected Nodes: 0/1
Unavailable Nodes: 1
  - some-node
```

Did I get something wrong or did I miss a step or is this a bug?

Thanks.

**Comment by kaworu** [comment]
@samstride please see [this comment](https://github.com/cilium/hubble/issues/599#issuecomment-911999467), in particular:

> The Helm method is the most flexible allowing different CA for ClusterMesh and Hubble, while the cilium-cli approach is the simplest one (using one CA for everything). Unfortunately, that makes them incompatible for now.

Note that this incompatibility should be solved with Cilium v1.12+ (see [the corresponding issue](https://github.com/cilium/cilium/issues/18278)).

**Comment by samstride** [comment]
@kaworu , thanks. Sorry my understanding is that this issue exists if you install cilium using helm but install hubble using cilium cli?

I originally installed cilium using the cli, I did an upgrade using kubectl + helm template, then installed hubble using cli.

Did the upgrade introduce the issue in my case?

**Comment by kaworu** [comment]
@samstride correct, I am guessing the upgrade regenerate the CAs and certificates in "the Helm way".

**Comment by jalberto** [comment]
Why isn't there an option to install Hubble using helm?

**Comment by samstride** [comment]
@kaworu , ahhh, I see. Got it. Thanks.

I tried the workaround documented in the comment and it works now.

Thanks for taking the time to assist.

**Comment by jalberto** [comment]
@Sh4d1 is this still being worked in SCW side?

**Comment by samstride** [comment]
@jalberto 
> Why isn't there an option to install Hubble using helm?

The [official docs](https://docs.cilium.io/en/v1.11/gettingstarted/hubble_setup/#enable-hubble-in-cilium) have this documentation to enable hubble in cilium.

```
helm upgrade cilium cilium/cilium --version 1.11.3 \
   --namespace kube-system \
   --reuse-values \
   --set hubble.relay.enabled=true \
   --set hubble.ui.enabled=true
```

**Comment by Sh4d1** [comment]
Hey! I changed team so I'm not aware, better to open up a support ticket or a feature request on scaleway's side to get more news I guess!

**Comment by jalberto** [comment]
Thanks, @Sh4d1 , support team on the tickets send me here, and you send me there, I am having a lot of fun

**Comment by kaworu** [comment]
https://github.com/cilium/cilium/issues/18278 has been fixed and since Cilium v1.12 both the Helm method and cilium-cli will use a single `cilium-ca`, so effectively the limitation should have been lifted.

**Comment by samstride** [comment]
@kaworu 

I am still experience a few issues with the latest version of the cli:

```sh
# k3s v1.24.3

cilium version
cilium-cli: v0.12.1 compiled with go1.18.5 on linux/amd64
cilium image (default): v1.12.0
cilium image (stable): v1.12.0
cilium image (running): v1.12.0

cilium hubble enable

Error: Unable to enable Hubble: unable to retrieve helm values secret kube-system/cilium-cli-helm-values: secrets "cilium-cli-helm-values" not found
```

**Comment by kaworu** [comment]
@samstride it seems to me that you're experiencing a different issue, unrelated to Hubble CA secrets. If correct, please open a new one and specify how Cilium was initially installed.

**Comment by MRostanski** [comment]
@samstride Same here, did you open any issue or ticket?

**Comment by kaworu** [comment]
@samstride @MRostanski if cilium was installed through Helm in your cluster, then I believe you are running into this issue https://github.com/cilium/cilium-cli/issues/959. If not, feel free to open a new one (preferably in the cilium-cli repository, as the underlying issue seems unrelated to Hubblem to me).

**Comment by samstride** [comment]
@MRostanski , sorry, no, I haven't opened an issue yet.

@kaworu, this is my timeline:

Cilium and hubble installation: https://github.com/cilium/hubble/issues/599#issuecomment-1088112092

Then I upgraded cilium and hubble based on your comment: https://github.com/cilium/hubble/issues/599#issuecomment-1088516144

Most recent action is that I have upgraded cilium via the CLI but cannot successfully upgrade hubble: https://github.com/cilium/hubble/issues/599#issuecomment-1214292978

**Comment by kaworu** [comment]
@samstride thank you for the clarification, I guess the issue can arise when Cilium was installed through a version of the cilium-cli that does not create the `cilium-cli-helm-values` secret (`<v1.11.0`), and then running `cilium hubble enable` with a later version requiring the secret (`>=v1.11.0`). So it's a slightly different path than installing through Helm first, but ultimately leading to the same issue. I would expect [this PR](https://github.com/cilium/cilium-cli/pull/1020) to fix the case you described as well.

_Please avoid commenting in this closed issue that was about another problem_ (Helm vs cilium-cli Hubble CA incompatibility). This would only add confusion to readers looking for an answer to either of theses issues. Instead, either open an new issue [here](https://github.com/cilium/cilium-cli/issues/new/choose) or comment on [this bug report](https://github.com/cilium/cilium-cli/issues/959). Thank you!
